language: csharp
mono: none
dotnet: 2.2
dist: xenial
solution: Glosharp.sln
script:
    - dotnet restore Glosharp/Glosharp.csproj
    - dotnet restore Glosharp/Glosharp.Test.csproj
    - dotnet build Glosharp/Glosharp.csproj
    - dotnet build Glosharp/Glosharp.Test.csproj
    - dotnet test Glosharp/Glosharp.Test.csproj