os: windows
solution: Glosharp.sln
script:
    - dotnet restore Glosharp/Glosharp.csproj
    - dotnet build Glosharp/Glosharp.csproj
    - dotnet restore Glosharp.Tests/Glosharp.Tests.csproj
    - dotnet build Glosharp.Tests/Glosharp.Tests.csproj
    - dotnet test Glosharp.Tests/Glosharp.Tests.csproj