version: 0.2.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\glosharp.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  GlosharpToken:
    secure: I0wuHAPn/9ocEETw1Q7WP2BCOFrfoD72nkxjsBxSoCEFbWzng5dmBY5YY8Ljr1M5
build:
  publish_nuget: true
  verbosity: normal
build_script:
  - cmd: dotnet restore Glosharp/Glosharp.csproj
  - cmd: dotnet build Glosharp/Glosharp.csproj
  - cmd: dotnet restore Glosharp.Tests/Glosharp.Tests.csproj
  - cmd: dotnet build Glosharp.Tests/Glosharp.Tests.csproj

test_script:
  - cmd: cd Glosharp.Tests
  - cmd: dotnet xunit