version: 0.2.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\glosharp.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  GlosharpToken:
    secure: I0wuHAPn/9ocEETw1Q7WP2BCOFrfoD72nkxjsBxSoCEFbWzng5dmBY5YY8Ljr1M5
nuget:
  project_feed: true
build_script:
- cmd: >-
    dotnet restore Glosharp/Glosharp.csproj

    dotnet build Glosharp/Glosharp.csproj

    dotnet restore Glosharp.Tests/Glosharp.Tests.csproj

    dotnet build Glosharp.Tests/Glosharp.Tests.csproj
after_build:
- cmd: >-
    cd Glosharp
    dotnet pack
test_script:
- cmd: >-
    cd Glosharp.Tests

    dotnet test
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: QAyphJuWeUivFv7GF8OBVdsKcBslk6xVSfHpAX0T274LyQwdEkrrbalWylFPJWjo