version: 0.2.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\Glosharp.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)
environment:
  GlosharpToken:
    secure: I0wuHAPn/9ocEETw1Q7WP2BCOFrfoD72nkxjsBxSoCEFbWzng5dmBY5YY8Ljr1M5
nuget:
  project_feed: true
build_script:
- cmd: >-
    dotnet restore Glosharp/Glosharp.csproj

    dotnet build Glosharp/Glosharp.csproj

    dotnet restore Glosharp.Tests/Glosharp.Tests.csproj

    dotnet build Glosharp.Tests/Glosharp.Tests.csproj
after_build:
- cmd: >-
    dotnet pack Glosharp/Glosharp.csproj -p:PackageVersion=%APPVEYOR_BUILD_VERSION% --version-suffix "ALPHA"
test_script:
- cmd: >-
    cd Glosharp.Tests

    dotnet test
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: QAyphJuWeUivFv7GF8OBVdsKcBslk6xVSfHpAX0T274LyQwdEkrrbalWylFPJWjo